### ISSUE TITLE
Can you update the translation of Online Demo?

### ISSUE THREAD

**Issue by WildfootW** [iredmail/iredadmin-pro-translation#13]

**Comment by iredmail** [comment]
Dear @WildfootW 

- The online demo will be updated each time we release a new version.
- May i know what issue you're experiencing with the online demo?

**Comment by WildfootW** [comment]
I just want to show it to my supervisor in a better state in order to buy your product. It is not attracting people if it contains some mistranslation.

**Comment by iredmail** [comment]
Only English and Simplifed Chinese are official, other translations were contributed by our users. Some translations may be out of date, and we have to wait for the contributors. Sorry. :(

**Comment by WildfootW** [comment]
So I updated some translation few times ago. Just want to see it applied in the demo.

**Comment by iredmail** [comment]
Updated moment ago. Thank you very much for the contribution. :)
